apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: mongodb 
 namespace: roboshop 
 # these are replica set labels 
 labels: 
  project: roboshop
  component: mongodb
  tier: db 
spec: 
 replicas: 1 
 selector: 
 # these labels are used to select pods
  matchLabels: 
   project: roboshop
   component: mongodb
   tier: db 
  # pod definition
 template: 
  metadata: 
    labels: 
     project: roboshop
     component: mongodb
     tier: db 
  spec: 
   containers: 
     - name: mongodb 
       image: siva3150/mongodb:v1 
       imagePullPolicy: Always 

    
--- 
apiVersion: v1 
kind: Service 
metadata: 
 name: mongodb
 namespace: roboshop  
spec: 
 selector: 
   project: roboshop
   component: mongodb
   tier: db 
 ports: 
  - protocol: TCP 
    port: 27017 # Service port 
    targetPort: 27017 # Container port 
    
  
  
 
  
   
 